In [1]:
import numpy as np
import pandas as pd

import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [2]:
path = "/content/drive/MyDrive/Machine Learning projects with Python/datasets/Health_insurance.csv"

In [3]:
df = pd.read_csv(path)
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
# explore the distribution of people who smoke and who do not:
df = df
figure = px.histogram(df, x = "sex", color = "smoker", title= "Number of Smokers")
figure.show()

In [6]:
df["sex"] = df["sex"].map({"female": 0, "male": 1})
df["smoker"] = df["smoker"].map({"no": 0, "yes": 1})
print(df.head())

   age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [8]:
# explore the distribution of the regions where people are living according to
# the dataset:
pie = df["region"].value_counts()
regions = pie.index
population = pie.values
fig = px.pie(df, values=population, names=regions)
fig.show()

In [10]:
x = np.array(df[["age", "sex", "bmi", "smoker"]])
y = np.array(df["charges"])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=72)

In [12]:
forest = RandomForestRegressor()

In [13]:
forest

RandomForestRegressor()

In [15]:
forest.fit(x_train, y_train)

RandomForestRegressor()

In [16]:
ypred = forest.predict(x_test)
data = pd.DataFrame(data={"Predicted Premium Amount": ypred})
print(data.head())

   Predicted Premium Amount
0              42001.177732
1              10491.640523
2               1340.802528
3               7078.773028
4              18508.409481